Bug 706667: Add missing limits.h include for UINT_MAX.
encode-basic.c uses 'UINT_MAX', which is available in the 'limits.h'
header.

In some configurations that build with zlib from [1], by chance
limits.h gets indirectly included when including 'z-imp.h' (the
includes are: 'z-imp.h' -> 'zlib.h' -> 'zconf.h' -> 'limits.h'), so
the build succeeds.

When using other zlib implementations however (for example from [2]),
limits.h is not necessarily included indirectly, which leads to the
build failing in the following way:

source/fitz/encode-basic.c: In function 'deflate_write':
source/fitz/encode-basic.c:343:27: error: 'UINT_MAX' undeclared (first use in this function)
  343 |         newbufsize = n >= UINT_MAX ? UINT_MAX : deflateBound(&state->z, n);
      |                           ^~~~~~~~
source/fitz/encode-basic.c:26:1: note: 'UINT_MAX' is defined in header '<limits.h>'; did you forget to '#include <limits.h>'?

Add the missing include, so that the build succeeds no matter if zlib
indirectly includes 'limit.h' or not.

Similarly, also add it in output-ps.c where it's also missing.

[1]: https://zlib.net/
[2]: https://github.com/zlib-ng/zlib-ng

Signed-off-by: Raphaël Mélotte <raphael.melotte@mind.be>